name: PR Auto with Together.ai

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  pr-auto:
    runs-on: ubuntu-latest
    steps:
      - name: Generate PR Description using Together.ai
        uses: vblagoje/pr-auto@main
        with:
          openai_api_key: ${{ secrets.TOGETHER_API_KEY }}
          openai_base_url: https://api.together.xyz/v1
          args: --generation_model mistralai/Mixtral-8x7B-Instruct-v0.1
